database:
  tables:
    - name: StromZaehler
      columns:
        - name: stromZaehlerID
          type: INTEGER
          constraints: [PRIMARY KEY, AUTOINCREMENT]
        - name: stromZaehlerNR
          type: TEXT
          constraints: [NOT NULL]
        - name: zeitpunkt
          type: DATETIME
          constraints: [NOT NULL]
        - name: stromZaehlerStand
          type: DECIMAL(7, 1)
          constraints: [NOT NULL]
      unique_constraints:
        - columns: [stromZaehlerNR, zeitpunkt]
      triggers:
        - name: prevent_quick_insert
          timing: BEFORE INSERT
          body: |
            SELECT CASE
              WHEN EXISTS (
                  SELECT 1
                  FROM StromZaehler
                  WHERE stromZaehlerNR = NEW.stromZaehlerNR
                    AND ABS(STRFTIME('%s', zeitpunkt) - STRFTIME('%s', NEW.zeitpunkt)) < 1
              )
              THEN RAISE(ABORT, 'Ein neuer Wert darf nicht innerhalb von 1 Sekunde hinterlegt werden')
            END;

    - name: Gaszaehler
      columns:
        - name: gasZaehlerID
          type: INTEGER
          constraints: [PRIMARY KEY, AUTOINCREMENT]
        - name: gasZaehlerNR
          type: TEXT
          constraints: [NOT NULL]
        - name: zeitpunkt
          type: DATETIME
          constraints: [NOT NULL]
        - name: gasZaehlerStand
          type: DECIMAL(8, 3)
          constraints: [NOT NULL]
      unique_constraints:
        - columns: [gasZaehlerNR, zeitpunkt]
      triggers:
        - name: prevent_quick_insert_gaszaehler
          timing: BEFORE INSERT
          body: |
            SELECT CASE
              WHEN EXISTS (
                  SELECT 1
                  FROM Gaszaehler
                  WHERE gasZaehlerNR = NEW.gasZaehlerNR
                    AND ABS(STRFTIME('%s', zeitpunkt) - STRFTIME('%s', NEW.zeitpunkt)) < 1
              )
              THEN RAISE(ABORT, 'Ein neuer Wert darf nicht innerhalb von 1 Sekunde hinterlegt werden')
            END;

  views:
    - name: stromzaehler_id_last_view
      definition: |
        SELECT stromZaehlerID, stromZaehlerNR, zeitpunkt, stromZaehlerStand
        FROM StromZaehler
        WHERE (stromZaehlerNR, zeitpunkt) IN (
          SELECT stromZaehlerNR, MAX(zeitpunkt)
          FROM StromZaehler
          GROUP BY stromZaehlerNR
        );

    - name: stromzaehler_id_view
      definition: |
        SELECT * 
        FROM StromZaehler;

    - name: stromzaehler_view
      definition: |
        SELECT stromZaehlerID, stromZaehlerNR, zeitpunkt, stromZaehlerStand
        FROM StromZaehler;

    - name: gaszaehler_id_last_view
      definition: |
        SELECT gasZaehlerID, gasZaehlerNR, zeitpunkt, gasZaehlerStand
        FROM Gaszaehler
        WHERE (gasZaehlerNR, zeitpunkt) IN (
          SELECT gasZaehlerNR, MAX(zeitpunkt)
          FROM Gaszaehler
          GROUP BY gasZaehlerNR
        );

    - name: gaszaehler_id_view
      definition: |
        SELECT * 
        FROM Gaszaehler;

    - name: gaszaehler_view
      definition: |
        SELECT gasZaehlerID, gasZaehlerNR, zeitpunkt, gasZaehlerStand
        FROM Gaszaehler;